#!/bin/bash

source lib/helpers.sh

require_command git
require_command tmux

if [ ! -d $HOME/.tat ]; then
  yak "cloning to $HOME/.tat"
  git clone git://github.com/ryandotsmith/tat.git $HOME/.tat
fi

grep tat.sh $HOME/.bash_profile > /dev/null
if [ $? -eq 1 ]; then
  yak "adding tat to the .bash_profile"
  echo '
# tux attach helper: tat
source $HOME/.tat/tat.sh
export CODE_ROOT_DIRS="$HOME:projects:$HOME/gits"' >> $HOME/.bash_profile

else
  yak "appears tat already setup in .bash_profile ... skipping setup"
fi

if [ ! -f $HOME/.tmux ]; then
  yak "creating you a good default $HOME/.tmux file"
  echo "set-option -g prefix C-A
setw -g aggressive-resize on
set -g base-index 1
bind-key a send-prefix" > $HOME/.tmux
fi
